---
- hosts: all
  become: yes
  gather_facts: no

  tasks:

  - name: "install atop"
    apt: name=atop state=latest

  # buggy?
  #- name: "copy atoprc to /etc/atoprc"
  #  copy: src=files/atoprc
  #        dest=/etc/atoprc
  #        owner=root group=root mode=644
  - name: "copy atoprc"
    shell: |
           cp files/atoprc /etc/atoprc
           chmod 644 /etc/atoprc

  - name: "stop atop service"
    service: name=atop
             state=stopped

  - name: "disable atop rc init script"
    shell: "update-rc.d atop disable"

  - name: "delete /var/log/atop/"
    file: path=/var/log/atop/ state=absent
