---
- hosts: compute
  become: no
  gather_facts: yes

  tasks:
  - name: "delete temp target directory"
    local_action: shell rm -rf ~/tmp/compute-benchmarks/

  - name: "create temp target directory"
    local_action: shell mkdir -p ~/tmp/compute-benchmarks/

  - name: "collect benchmark metrics"
    fetch: src=/home/salvus/logs/metrics-{{ ansible_hostname }}.log
           dest=~/tmp/compute-benchmarks/
           flat=yes

  - name: "move files to ops project"
    local_action: shell ./move-compute-benchmarks-to-ops-project.py

  #- name: "get host of smc ops project"
  #  local_action: shell ./smc-project-host.py b97f6266-fe6f-4b40-bd88-9798994a04d1
  # register: ops

  #- name: "copy benchmark files to ops project"
  #  copy: src=%s
  #        dest=/projects/b97f6266-fe6f-4b40-bd88-9798994a04d1/benchmarks/
  #        owner=1128707724
  #        group=1128707724
  #        mode=u=rw,go={{ ops.stdout }}
