---
- hosts: compute
  become: yes
  gather_facts: no

  tasks:

  - name: "install per-user security limits"
    template: src="files/compute-security-limits.conf"
              dest="/etc/security/limits.d/99-smc.cfg"
              owner=root group=root mode=644
    tags: "install"
