---
- hosts: compute
  become: salvus
  gather_facts: no

  tasks:

  - name: "install the google python lib"
    pip: executable=pip
         state=latest
         name=google-api-python-client

  - name: "install custom metric running project"
    copy: src="files/compute_metrics.py" dest="~/bin/compute_metrics.py"
          owner=salvus group=salvus mode=500
    tags: "install"

  # don't change the cron: name enty, it's used to identify it!
  - name: "install crontab entry"
    cron: name="report active projects"
          state=present
          user=salvus
          job="$HOME/bin/compute_metrics.py"
    tags: "cron"
