---
- hosts: compute
  become: yes
  gather_facts: no

  tasks:

  - name: "install kernel command line args for cgroup swap accounting"
    copy: src="files/kernel-cgroup-swap-accounting.cfg"
          dest="/etc/default/grub.d/99-smc.cfg"
          owner=root group=root mode=644
    tags: "install"

  - name: "update grub"
    command: "update-grub"