---
- hosts: web:compute:storage:db
  become: salvus
  strategy: free
  gather_facts: no

  tasks:

  - name: "custom_metric dir"
    file: state=directory
          dest=~/custom_metric/
          owner=salvus group=salvus mode=700

  - name: "custom metric files"
    copy: src="{{ item[0] }}"
          dest="{{ item[1] }}"
          owner=salvus group=salvus mode=600
    with_together:
      - [ "secrets/creds.dat",         "files/record_metric.py"]
      - [ "~/custom_metric/creds.dat", "~/custom_metric/record_metric.py"]


