---
- hosts: compute
  become: yes
  gather_facts: no

  tasks:

  - name: 'Additional packages (mainly for users, not building) - LaTeX packages'
    apt: "name={{ item }} install_recommends=yes state=latest"
    tags:
    - install
    - update
    with_items:
    - aspell-*
    - dot2tex
    - lilypond
    - texlive-full
    - texlive-bibtex-extra
    - texlive-extra-utils
    - texlive-fonts-extra
    - texlive-fonts-extra-doc
    - texlive-formats-extra
    - texlive-generic-extra
    - texlive-latex-extra
    - texlive-latex-extra-doc
    - texlive-math-extra
    - texlive-plain-extra
    - texlive-xetex
    - texlive-lang-all
    - texlive-latex-base
    - texlive-latex-base-doc
    - texlive-latex-extra
    - texlive-latex-extra-doc
    - texlive-latex-recommended
    - texlive-latex-recommended-doc
    - texlive-latex3
    - texlive-luatex
    - asymptote
    - asymptote-doc
    - biber
    - chktex
    - dblatex
    - dot2tex
    - feynmf
    - fig2ps
    - fonts-mathjax
    - fragmaster
    - lacheck
    - latex-cjk-all
    - latexdiff
    - latexmk
    - libpod-latex-perl
    - prerex
    - preview-latex-style
    - prosper
    - tipa
    - vim-latexsuite
    # - auctex # installs some trigger, which takes a very long time to run after each package upgrade

  - name: 'create target directory'
    tags: latex
    file: path=/usr/local/share/latexmk/ state=directory

  # support for sagetex for latexmk by default
  # see https://github.com/dandrake/sagetex/wiki
  - name: "copy latexmkrc file to /usr/local/share/latexmk/"
    tags: latex
    copy: src=files/latexmkrc
          dest=/usr/local/share/latexmk/latexmkrc
          owner=root group=root mode=644