---
# deploy and configure Monit
# https://mmonit.com/monit/
# https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-monit

- hosts: web
  become: yes
  gather_facts: no

  tasks:

  - name: "install monit"
    apt: state=latest name=monit

  - name: "configure monit check interval"
    lineinfile: dest="/etc/monit/monitrc"
                regexp="^\s+set\s+daemon"
                line="  set daemon 60"
    notify: restart monit

  - name: "configure monit start delay"
    lineinfile: dest="/etc/monit/monitrc"
                insertafter="^\s+set\s+daemon"
                regexp="^\s+with\s+start\s+delay"
                line="  with start delay 60"
    notify: restart monit

# http localhost interface, also used for CLI tools
# set httpd port 2812 and
#     use address localhost  # only accept connection from localhost
#     allow localhost

  - name: "configure monit http localhost interface"
    lineinfile: dest="/etc/monit/monitrc"
                insertbefore="^#\s+set\s+httpd\s+port"
                regexp="{{ item.regexp }}"
                line="{{ item.line }}"
    with_items:
      - { regexp: '^set httpd port',            line: 'set httpd port 2812 and' }
      - { regexp: '^\s+use address localhost',  line: '  use address localhost' }
      - { regexp: '^\s+allow\slocalhost',       line: '  allow localhost' }
    notify: restart monit

  handlers:

  - name: restart monit
    service: name=monit state=restarted
