---
- hosts: admin0
  become: yes
  gather_facts: no

  tasks:
  - name: "update templates"
    local_action: shell ./get_templates.py

- hosts: compute
  become: yes
  gather_facts: no

  tasks:
  - name: "delete existing templates directory"
    file: path=/projects/templates
          state=absent

  - name: "push template files"
    copy: src=files/templates
          dest=/projects/
          owner=salvus
          group=salvus
          directory_mode="u=rx,g=rx,o=rx"
          mode="u=r,g=r,o=r"
