---
- hosts: storage
  become: salvus
  gather_facts: no

  tasks:

  - name: "install the google python lib"
    pip: executable=pip
         state=latest
         name=google-api-python-client

  - name: "install custom metric running project"
    copy: src="files/storage_rsync_metrics.py" dest="~/bin/storage_rsync_metrics.py"
          owner=salvus group=salvus mode=500
    tags: "install"

  # don't change the cron: name enty, it's used to identify it!
  - name: "install crontab entry"
    cron: name="report concurrent rsyncs"
          state=present
          user=salvus
          job="$HOME/bin/storage_rsync_metrics.py"
    tags: "cron"
