- name: tcp ports of compute nodes
  gather_facts: False
  hosts: compute

  tasks:
  - name: get the current port for a compute node
    command: cat /projects/conf/compute.port
    register: portnumber
  - set_fact: port="{{ portnumber.stdout }}"
  - debug: var="{{ portnumber.stdout }}"


- name: tcp connections for compute <-> web
  gather_facts: False
  hosts: web

  tasks:
  - name: echo the port
    shell: 'echo -n {{ item }}:; lsof -i :{{ hostvars[item].port }} | cut -d" " -f3 | sort | uniq -c | tail -n +2 | cut -c-8 | tr -d "\n"'
    with_items: "{{ groups['compute'] }}"
    register: tcpcount

  - debug: msg=item
    with_items: "tcpcount.results | selectattr('changed') | map(attribute='stdout') | list"

#  - debug: msg={{ item.item }}
#    with_items: "tcpcount.results | selectattr('changed') | map(attribute='stdout') | list"
#    #with_items: tcpcount.results
