---
# setting up tmux config files for salvus
- hosts: all
  become: no
  gather_facts: no
  tasks:

  - name: "install .tmux.conf file"
    template: src=files/tmux-config.conf
              dest="{{ lookup('env','HOME') }}/.tmux.conf"
              owner=salvus group=salvus mode="u=rw,go="


- hosts: compute
  become: no
  gather_facts: no
  strategy: free
  tasks:

  - name: "Ensures ~/.tmux dir exists"
    file: path="{{ lookup('env','HOME') }}/.tmux"
          state=directory

  - name: "install the tmux-compute.conf file at /home/salvus/.tmux/compute.conf"
    template: src=files/tmux-compute.conf
              dest="{{ lookup('env','HOME') }}/.tmux/compute.conf"
              owner=salvus group=salvus mode="u=r,go="

