---
- hosts: compute
  become: yes
  gather_facts: no

  tasks:

  - name: "set UMASK globally"
    lineinfile: dest="/etc/login.defs"
                regexp="^UMASK"
                line="UMASK 077"

  - name: "show umask in login.defs"
    shell: "/bin/grep -e '^UMASK' /etc/login.defs | cut -c 7-"
    register: login_umask
    tags: show

  - debug: msg="UMASK in /etc/login.defs {{ login_umask.stdout }}"
    tags: show
