---
- hosts: compute
  become: salvus
  gather_facts: yes

  tasks:

  - name: "install video chat analyzer"
    copy: src="files/video_chats.py" dest="~/bin/video_chats.py"
          owner=salvus group=salvus mode=500
    tags: "install"

  - name: "run video chat analyzer"
    shell: "python3 /home/salvus/bin/video_chats.py"
    tags: "run"
    become: true

  - name: "collect video chat data"
    fetch: src=/home/salvus/tmp/video_chats-{{ ansible_hostname }}.csv.bz2
       dest=~/tmp/
       flat=yes
    tags: "collect"
    become: true

  - name: "export to stats project"
    local_action: shell ./export-video-chat.py
    tags: "export"