---
- hosts: web
  become: yes
  gather_facts: no

  tasks:

  - name: "system wide pip packages"
    pip:  executable=pip
          state=latest
          name={{ item }}
    with_items:
       - google-api-python-client

  - name: "system wide pip3 packages"
    pip:  executable=pip3
          state=latest
          name={{ item }}
    with_items:
       - dateutils

