---
- hosts: web
  become: yes
  gather_facts: no

  tasks:

  #- name: "hub*.log logrotate entry"
  #  template: src=files/hub-log-logrotate
  #            dest=/etc/logrotate.d/smc-hub-log
  #            owner=root group=root mode=644

  - name : "logrotate doesn't work"
    file:  path=/etc/logrotate.d/smc-hub-log
           state=absent

