---
- hosts: web
  become: yes
  gather_facts: no

  tasks:

  - name: "apt-get update & upgrade"
    apt: update_cache=yes cache_valid_time=3600 upgrade=safe
    # that's one hour, upgrade safe uses aptitude's heuristics

  - name: "install packages"
    apt: state=latest name={{ item }}
    with_items:
      - aptitude
      - python-apt
      - python-pip
      - python-dateutil
      - python-tz
      - python-scipy
      - python3-pip
      - python3-scipy
    tags:
      - install

