---
# rolling update of the hubs
- name: "restart hubs"
  hosts: web
  serial: 1
  gather_facts: no
  become: salvus

  tasks:
  - name: "pause a bit except for the first one"
    pause: minutes=3
    when: inventory_hostname != "web0"

  - name: "restart hub"
    shell: restart_hub
    register: restart_output

  - debug: "msg=stdout: {{ restart_output.stdout }}"
  - debug: "msg=stderr: {{ restart_output.stderr }}"
