---
- hosts: web
  become: yes
  gather_facts: no

  tasks:

  - name: "copy zendesk secret"
    copy: src=secrets/zendesk
          dest=/home/salvus/smc/src/data/secrets/zendesk
          owner=salvus group=salvus mode=400


