---
- hosts: web
  become: salvus
  gather_facts: no

  tasks:

  - name: "log hub analyze script"
    copy: src=files/hub-log-analyze.py
          dest=~/bin/hub-log-analyze.py
          owner=salvus group=salvus mode=500
    tags: "scripts"

  # don't change the cron: name enty, it's used to identify it!
  - name: "install crontab entry"
    cron: name="hub.log analyze"
          state=present
          user=salvus
          job="$HOME/bin/hub-log-analyze.py $HOME/logs/hub?.log"
    tags: "cron"
