---
# checks on localhost, if the rethinkdb proxy works and knows about the
# projects table in the smc db
# install via: $ ansible-playbook web-check-rethinkdb-proxy.yaml
- hosts: web
  become: salvus
  gather_facts: no

  tasks:

  - name: "install check rethinkdb hub script"
    copy: src=files/check_rethinkdb_proxy.py
          dest=~/bin/check_rethinkdb_proxy.py
          owner=salvus group=salvus mode=500
    tags: "script"

  # don't change the cron name entry, it's used to identify it!
  - name: "install crontab check rethinkdb proxy"
    cron: name="check rethinkdb proxy"
          state=absent
          user=salvus
          job="$HOME/bin/check_rethinkdb_proxy.py > ~/.check_rethinkdb_proxy.run 2>&1"
    tags: "cron"

