apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    run : disk-space
  name: disk-space
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/disk-space
spec:
  template:
    metadata:
      labels:
          daemon : disk-space
    spec:
      containers:
      - image: "{image}"
        imagePullPolicy: {pull_policy}
        name: disk-space
        volumeMounts:
        - name: ssh
          mountPath: /node/root/.ssh
        - name: etc
          mountPath: /node/etc/
        resources:
          requests:
            memory: "40Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
            cpu: "100m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ssh
        hostPath:
          path: /root/.ssh
      - name: etc
        hostPath:
          path: /etc
