# The point of this service is to make it easy for any node to find all the other nodes.

apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-cluster
spec:
  ports:
    - port: 29015
      targetPort: cluster-port
  selector:
    db: rethinkdb
    role: replica