kind: "Service"
apiVersion: "v1"
metadata:
  name: rethinkdb-cluster
spec:
  ports:
  - port: 29015
    targetPort: 29015

---

kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: rethinkdb-cluster
subsets:
-
  addresses: {ips}
  ports:
    -
      port: 29015

---

kind: "Service"
apiVersion: "v1"
metadata:
  name: rethinkdb-driver
spec:
  ports:
  - port: 28015
    targetPort: 28015

---

kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: rethinkdb-driver
subsets:
-
  addresses: {ips}
  ports:
    -
      port: 28015

