apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: null
  generation: 1
  labels:
    run: rethinkdb-proxy
  name: rethinkdb-proxy
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/rethinkdb-proxy
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      run: rethinkdb-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: rethinkdb-proxy
    spec:
      containers:
      - image: {image}
        imagePullPolicy: {pull_policy}
        name: rethinkdb-proxy
        terminationMessagePath: /dev/termination-log
        ports:
        - containerPort: 28015
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /health.py
          initialDelaySeconds: 30
          timeoutSeconds: 3
        volumeMounts:
        - name: secret-rethinkdb
          mountPath: /secrets/rethinkdb/
          readOnly: true
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          requests:
            memory: "1000Mi"
            cpu: "400m"
          limits:
            memory: "2000Mi"
            cpu: "2000m"
      volumes:
        - name: secret-rethinkdb
          secret:
            secretName: rethinkdb-password
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
